export { default as sass } from './imgs/Sass.svg'
export { default as css } from './imgs/css.svg'
export { default as html } from './imgs/html.svg'
export { default as js } from './imgs/JavaScript.svg'
export { default as ts } from './imgs/typeScript.svg'
export { default as react } from './imgs/React.svg'
export { default as figma } from './imgs/Figma.svg'
export { default as vsCode } from './imgs/VSCode.svg'
export { default as win11 } from './imgs/Windows 11.svg'
export { default as unkw } from './imgs/unknownSkill.svg'
